#+title: EKT / Emacs Keyboard Translation

* Description

Use Emacs and your keyboard layout.

Note: you need xkb-switch or im-select to be available in PATH.

Note 2: you can use libxkbswitch and ffi on linux.

This package helps you build keymaps to substitute ~key-translation-map~.

For defining translation maps see ~ekt/make-translation~ and ekt-ru.el.

If you only use one keyboard layout beside US, you can just substitute
~key-translation-map~ yourselves.

Otherwise, try automated switching.  Emacs runs xkb-switch every second to
check your active layout and activate the right translation map, which then
translates key presses to bindings that Emacs knows.

To start automated key translation, run ~ekt/start-layout-watcher~. To stop,
execute ~ekt/stop-layout-watcher~. Please note that there may be a delay
before new ~key-translation-map~ activation.

* Examples

** use-package

Clone in your ~load-path~ first.

*** use-package
#+begin_src emacs-lisp
(use-package! ekt-ru-qwerty
  :init
  (setq ekt/default-layout "us")
  ;; uncomment for autoswitching
  ;; :hook (after-init . ekt/start-layout-watcher)
  :config
  (ekt-ru-qwerty/make-translation "ru")
  (setq key-translation-map
        (symbol-value (gethash "ru" ekt/key-translation-maps))))

;; autoswitching
(use-package ekt
    :hook (after-init . ekt/start-layout-watcher)
    ;; optional init
    :init
    (require 'ekt-ru))

;; one layout
(use-package ekt-ru
  :config
  (setq key-translation-map ekt/ru-key-translation-map))
#+end_src

** doom emacs

*** packages.el

  #+begin_src emacs-lisp
  (package! ekt
    :recipe (:host github :repo "teu5us/ekt"))
  #+end_src

*** config.el

#+begin_src emacs-lisp
(use-package! ekt-ru-qwerty
  :init
  (setq ekt/default-layout "us")
  :config
  (ekt-ru-qwerty/make-translation "ru")
  (setq key-translation-map
        (symbol-value (gethash "ru" ekt/key-translation-maps))))
#+end_src

** libxkbswitch on linux with doom emacs

#+begin_src emacs-lisp
(use-package! ekt-ru-qwerty
  :after ffi
  :init
  (setq ekt/libxkbswitch
        "/nix/store/8g89p11rjj9hbi4hjlp6ysmjf4cxqw7h-xkb-switch-1.8.5/lib/libxkbswitch.so")
  (setq ekt/use-ffi t)
  (setq ekt/default-layout "us")
  :config
  (ekt-ru-qwerty/make-translation "ru")
  (setq key-translation-map
        (symbol-value (gethash "ru" ekt/key-translation-maps))))
#+end_src
